---
title: "Publications"
---

***
[Google Scholar](https://scholar.google.com/citations?user=8rf72h8AAAAJ&hl=en)

[Research Gate](https://www.google.com/url?q=https%3A%2F%2Fwww.researchgate.net%2Fprofile%2FDaniel_Forster&sa=D&sntz=1&usg=AFQjCNGZHyAXw6hNKW0ND-HvvABnbhwR3g)

***

Smith, A., Pedersen, E. J., **Forster, D. E.**, McCullough, M. E., & Lieberman, D. (in press). Cooperation: The roles of interpersonal value and gratitude. Evolution and Human Behavior. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2Fac.els-cdn.com%2FS1090513817300818%2F1-s2.0-S1090513817300818-main.pdf%3F_tid%3Db0c5ced8-9e28-11e7-8c29-00000aacb35e%26acdnat%3D1505928506_923535e51917fc314dc386a001522884&sa=D&sntz=1&usg=AFQjCNEVb23dICjJNtcb2g9gwUX1UL3QeA)

McAuliffe, W. H. B., **Forster, D. E.**, Phillipe, J., & McCullough, M. E. (in press). Digital altruists: Resolving key questions about the empathy-altruism hypothesis in an internet sample. Emotion. [**[PDF]**](https://drive.google.com/open?id=0B4dBnjOhmzO8d1RCdjg3Z0lTdTQ)

**Forster, D. E.**, Pedersen, E. J., Smith, A., McCullough, M. E. & Lieberman, D. (2017). Benefit valuation predicts gratitude. Evolution and Human Behavior, 38(1), 18-26. [**[PDF]**](https://ac.els-cdn.com/S1090513816301131/1-s2.0-S1090513816301131-main.pdf?_tid=2979afd8-9fd8-11e7-bcb8-00000aab0f6c&acdnat=1506113821_eab8211eeb2358ef5720ad7976320c89)

Krimsky, M., **Forster, D. E.**, Llabre, M. M., & Jha, A. P. (2017). The influence of time on task on mind wandering and visual working memory. Cognition 169, 84-90. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2Fac.els-cdn.com%2FS001002771730224X%2F1-s2.0-S001002771730224X-main.pdf%3F_tid%3Dacd20e26-9e29-11e7-94ef-00000aab0f27%26acdnat%3D1505928929_0574df546cfd8ddd410398eee621ebad&sa=D&sntz=1&usg=AFQjCNHQi7fbhv_H3RJ_B_FlGahJc9eaeA)

Spencer-Rodgers, J., Major, B., **Forster, D. E.**, & Peng, K. (2016). The power of affirming group values: Group affirmation buffers the self-esteem of women exposed to blatant sexism. Self and Identity, 15(4), 413-431. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2Fwww.tandfonline.com%2Fdoi%2Fpdf%2F10.1080%2F15298868.2016.1145593%3FneedAccess%3Dtrue%26&sa=D&sntz=1&usg=AFQjCNG80KFgkz_Fh71FvoTeyS_DkZLLMA)

Carter, E. C., Kofler, L. K., **Forster, D. E.**, & McCullough, M. E. (2015). A series of meta-analytic tests of the depletion effect: Self-control does not seem to rely on a limited resource. Journal of Experimental Psychology: General, 144(4), 796-815. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2Fciteseerx.ist.psu.edu%2Fviewdoc%2Fdownload%3Fdoi%3D10.1.1.719.8430%26rep%3Drep1%26type%3Dpdf&sa=D&sntz=1&usg=AFQjCNFR2Z9KGp_TaKKX7IdKgb9k9NCIFA)

Carver, C. S., Johnson, S. L., McCullough, M. E., **Forster, D. E.**, & Joorman, J. (2014). Adult personality correlates of childhood adversity. Frontiers in Psychology. 5:1357. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2Fjournal.frontiersin.org%2Farticle%2F10.3389%2Ffpsyg.2014.01357%2Ffull&sa=D&sntz=1&usg=AFQjCNFLimSdtB5BbQgsacrpvtFo0iLpMQ)

Pedersen, E. J., **Forster, D. E.**, & McCullough, M. E. (2014). Life history, code of honor, and emotional responses to inequality in an economic game. Emotion, 14(5), 920-929. [**[PDF]**](http://www.google.com/url?q=http%3A%2F%2F129.171.236.12%2Ffaculty%2Fmmccullough%2FPapers%2FPedersen%2520et%2520al%2520%2520Emotion%2520%28in%2520press%29.pdf&sa=D&sntz=1&usg=AFQjCNHtxBf34oGyUJp_1jbgEKPk6b0wRg)